config/routes.rb
Frontend::Application.routes.draw do
  resources :nodes

  match '/nodes/:id/thresh_defaults', :controller => 'nodes', :action => 'thresh_defaults', :via => 'post'

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :node
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_one :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  # GET /nodes
  # GET /nodes.xml
  
  def index
    @racks = {}
    @layout =[]
    # @nodes = Location.all(:order => "rack ASC , rank ASC , hostname ASC")
    # @locations = Location.all
    d_racks = Location.all(:select => "DISTINCT rack")
    d_racks.each {|x| @layout[x.rack] = Location.find_all_by_rack(d_racks[x.rack].rack).size }

    @coordinates = Array.new(@layout.size){Array.new(@layout.max)}
    
    @layout.max.times do |rank| # fullest rack
      @layout.size.times do |rack| # number of racks, assumes sequential rack numbering; TODO: FIXME
        if t = Location.find_by_rack_and_rank(rack,rank)
          @coordinates[rack][rank] = t
        end
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.xml
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.xml
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.xml
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to(@node, :notice => 'Node was successfully created.') }
        format.xml  { render :xml => @node, :status => :created, :location => @node }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.xml
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to(@node, :notice => 'Node was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.xml
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to(nodes_url) }
      format.xml  { head :ok }
    end
  end
  
  def thresh_defaults
    @node = Node.find(params[:id])
    @node.thresh_unc = @node.def_thresh_unc
    @node.thresh_ucr = @node.def_thresh_ucr
    @node.thresh_unr = @node.def_thresh_unr
    @node.save
    respond_to do |format|
      format.html { redirect_to(@node, :notice => "Thresholds were reset to default values") }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!--  <title>Frontend</title> -->
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>

  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :thresh_unc, "Threshold: Upper Non-Critical" %><br />
    <%= f.text_field :thresh_unc %>
  </div>

  <div class="field">
    <%= f.label :thresh_ucr, "Threshold: Upper Critical" %><br />
    <%= f.text_field :thresh_ucr %>
  </div>

  <div class="field">
    <%= f.label :thresh_unr, "Threshold: Upper Non-Recoverable" %><br />
    <%= f.text_field :thresh_unr %>
  </div>

  <div class="actions">
    <%= f.submit("Update " + @node.hostname) %> 
  </div>

  <div class="actions2">  
    <%= form_tag('thresh_defaults') do %>
      <div><%= submit_tag("Defaults") %></div>
    <% end %>
 </div>

<% end %>

app/views/nodes/edit.html.erb
<h1>Edit <%= @node.hostname %> thresholds</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<title>Frontend</title>
<h1>Physical Layout</h1>


<table style="border-spacing: 20px 0px">
<% @layout.max.times do |rank| %> <!-- #fullest rack -->
  <tr>
  <% @layout.size.times do |rack| %> <!-- #number of racks, assumes sequential rack numbering  -->
    <td>
    <% if rank == 0 %> <!-- drop in a title for each column (rack) -->
      <h3><center>Rack <%= rack %></center></h3>
    <% end %>
    <% if location = @coordinates[rack][rank] %>
      <%= link_to(image_tag("rrd_graphs/small/#{location.node.hostname}.png"),location.node) %>
    <% end %>
    </td>
  <% end %>
  </tr>
<% end %>
</table>

<!--<%= link_to 'New Node', new_node_path %> -->
<br />

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

  <title><%= @node.hostname %></title>

<table style="border-spacing: 10px 0px">

  <tr>
    <td colspan="1" rowspan="7">
      <%= image_tag("rrd_graphs/#{@node.hostname}.png") %>
    </td>

    <td>
      <b>Ambient temperature:</b>
    </td>
    <td>
      <%= @node.cur_temp %>&deg;C
    </td>
  </tr>

  <tr>
    <td>
      <b>Temperature status:</b> 
     </td>
     <td>
      <%= @node.temp_status %>
    </td>
  </tr>

  <tr>
    <td>
      <b>Watermark high:</b>
    </td>
    <td>
      <%= @node.watermark_high %>&deg;C 
    </td>
  </tr>

  <tr>
    <td>
      <b>Watermark low:</b>
    </td>
    <td>
      <%= @node.watermark_low %>&deg;C 
    </td>
  </tr>

  <tr>
    <td>
      <b>Threshold, Upper Non-Critical:</b>
    </td>
    <td>
      <%= @node.thresh_unc %>&deg;C
    </td>
  </tr>

  <tr>
    <td>
      <b>Threshold, Upper Critical:</b>
    </td>
    <td>
      <%= @node.thresh_ucr %>&deg;C
    </td>
  </tr>

  <tr>
    <td>
      <b>Threshold, Upper Non-Recoverable:</b>
    </td>
    <td>
      <%= @node.thresh_unr %>&deg;C
    </td>
  </tr>

</table>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>